Possible to run simulation asynchronously
But the async version causes panics

    thread 'main' panicked at 'could not create DataFrame from iterator: Duplicate("Column with name: '1' has more than one occurrences")', /Users/evenson/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.22.7/src/frame/upstream_traits.rs:11:27